name: ci/cd
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build:
    runs-on: all
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Declare variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "run_name=$(echo "$GITHUB_REPOSITORY" | sed "s/\//_/")" >> "$GITHUB_ENV"
      - name: Build docker
        run: |
          docker build -t ${{ gitea.repository }}:${{ env.sha_short }} -t ${{ gitea.repository }}:latest .
      - name: Start docker
        run: |
          docker container rm -f ${{ env.run_name }} || true
          docker run -d --network=web --restart unless-stopped --name ${{ env.run_name }} ${{ gitea.repository }}:${{ env.sha_short }}
          /usr/local/bin/caddycontrol -host www.flach.io -dial ${{ env.run_name }}:80 &


      - run: echo "🍏 This job's status is ${{ job.status }}."


